spring:
  datasource:
    url: jdbc:mysql://localhost:3306/synchronous
    username: root
    password: Chetana@7411



server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
